"""Add admin

Revision ID: 380489d3f27b
Revises: 353bdace1dec
Create Date: 2022-10-31 12:14:39.132375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380489d3f27b'
down_revision = '353bdace1dec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'admin')
    # ### end Alembic commands ###
